### ISSUE TITLE
Poposal: puts vendor.json information into vendored package directory

### ISSUE THREAD

**Issue by neelance** [kardianos/govendor#115] opened 2016-03-21 14:44 UTC
We just recently started using govendor and we already have some weird inconsistencies between the vendor.json file and the actually vendored packages. Those inconsistencies might be avoided by putting a vendor.json file into each vendored package instead of having one file for all. That way, if some vendored package gets deleted, the corresponding vendor.json is also gone. What do you think?

**Comment by kaey** [comment] 2016-03-21 15:13
What kind of inconsistencies? If there is a bug please report it (preferably with steps to reproduce) and it will be fixed.

**Comment by neelance** [comment] 2016-03-21 15:48
What does it mean for govendor if there is an entry in vendor.json but the corresponding package does not exist in the `vendor` directory?

**Comment by kardianos** [comment] 2016-03-21 16:15
Hi @neelance 

One of the [use cases](https://github.com/kardianos/govendor/blob/master/doc/whitepaper.md) that are possible with govendor is to use it to keep track of the revision a package uses, but not checkin the source files in the vendor folder.  While I do not personally normally recommend this, it is valid.

If the entry still exists in govendor but does not exist in the vendor folder, "govendor status" will report it. It is recommended to use `govendor remove` to remove those entries from the vendor folder and any remaining files.

**Closed** 2016-03-27 23:09 UTC

**Comment by influx6** [comment] 2016-03-28 05:36
Am in agreement with @kardianos, since the vendor.json file contains the needed information, it's a simple thing to update or readd them at their specific revision. Personally have found this feature somewhat useful at times. But your needs may differ. But fragmenting multiple vendor.json file down the tree is not really good management, it should be there to flatten out the dependencies regardless of depth.
