### ISSUE TITLE
go-sqlite3 build error because "code" folder missing

### ISSUE THREAD

**Issue by harobed** [kardianos/govendor#71] opened 2015-12-24 12:17 UTC
When I try to use ```go-sqlite3``` with govendor, I've this error : 

```
$ go build
# gobookmark/vendor/github.com/mattn/go-sqlite3
In file included from vendor/github.com/mattn/go-sqlite3/backup.go:9:
./sqlite3-binding.h:2:10: fatal error: 'code/sqlite3-binding.h' file not found
#include "code/sqlite3-binding.h"
         ^
1 error generated.
```

With ? before govendor, this is the ```go-sqlite3``` directory structure :

```
$ tree
.
├── LICENSE
├── README.md
├── _example
│   ├── custom_func
│   │   └── main.go
│   ├── hook
│   │   └── hook.go
│   ├── mod_regexp
│   │   ├── Makefile
│   │   ├── extension.go
│   │   └── sqlite3_mod_regexp.c
│   ├── mod_vtable
│   │   ├── Makefile
│   │   ├── extension.go
│   │   ├── picojson.h
│   │   └── sqlite3_mod_vtable.cc
│   └── simple
│       └── simple.go
├── backup.go
├── callback.go
├── callback_test.go
├── code
│   ├── sqlite3-binding.c
│   ├── sqlite3-binding.h
│   └── sqlite3ext.h
├── doc.go
├── error.go
├── error_test.go
├── sqlite3-binding.c
├── sqlite3-binding.h
├── sqlite3.go
├── sqlite3_fts3_test.go
├── sqlite3_icu.go
├── sqlite3_libsqlite3.go
├── sqlite3_load_extension.go
├── sqlite3_omit_load_extension.go
├── sqlite3_other.go
├── sqlite3_test
│   └── sqltest.go
├── sqlite3_test.go
└── sqlite3_windows.go
```

after "vendoring" :

```
$ tree vendor/github.com/mattn/go-sqlite3/
vendor/github.com/mattn/go-sqlite3/
├── LICENSE
├── README.md
├── backup.go
├── callback.go
├── doc.go
├── error.go
├── sqlite3-binding.c
├── sqlite3-binding.h
├── sqlite3.go
├── sqlite3_icu.go
├── sqlite3_libsqlite3.go
├── sqlite3_load_extension.go
├── sqlite3_omit_load_extension.go
├── sqlite3_other.go
└── sqlite3_windows.go

0 directories, 15 files
```

```sqlite3-binding.* ``` aren't in ```code``` folder !

**Comment by kardianos** [comment] 2015-12-24 20:14
This is a duplicate of #61 
I plan to add a -tree option to allow copying all nested folders too.
For now, copy by hand :/

**Comment by kardianos** [comment] 2016-01-22 17:04
Fixed on master now.
`govendor add github.com/mattn/go-sqlite3/^`
will copy package and all sub-folders.

**Closed by kardianos** 2016-01-22 17:04 UTC
