### ISSUE TITLE
`add` vs `update` vendoring differences 

### ISSUE THREAD

**Issue by Ropes** [kardianos/govendor#207] opened 2016-08-19 23:59 UTC
I've caught an interesting difference between what the `add` and `update` commands effectively vendor.and have been able to reproduce consistently. On our main repo starting from a freshly init'd vendor dir, run `govendor add +e` then commit; then without making any changes to `vendor/` or the GOPATH, running `govendor update +v` results in the following diff:
```
                {
-                       "checksumSHA1": "uxjcsegqHgTzDpB+2KNxot4+n/s=", //`add`
+                       "checksumSHA1": "FKKKcgIllaiumb4CuoFGQyHjp4g=", //`update`
                        "origin": "github.com/nats-io/gnatsd/vendor/github.com/nats-io/nuid",
                        "path": "github.com/nats-io/nuid",
-                       "revision": "4f84f5f3b2786224e336af2e13dba0a0a80b76fa", //`add`
-                       "revisionTime": "2016-02-25T11:17:58Z"
+                       "revision": "86e883ce7d54d925e3018a761da38074eb732218", //`update`
+                       "revisionTime": "2016-06-09T19:49:34Z"
                },
```
The bizarre thing was the `"revision": "4f84f5f3b2786224e336af2e13dba0a0a80b76fa"` of `github.com/nats-io/gnatsd` from the `add` command, that revision doesn't exist in that repository.  

* `86e883...` is from `github.com/nats-io/gnatsd` checked in out in my GOPATH.
* `4f84f5f3...` revision is coming from a (now unused thanks to `gnatsd/vendor/`) checkout of `github.com/nats-io/nuid` in my GOPATH. 

Our project doesn't directly import `github.com/nats-io/nuid`, however gnatsd requires it and thus it was installed in the GOPATH(probably prior to `gnatsd/vendor/` being created). 

The codepath for `add` creates a package definition for `github.com/nats-io/nuid` and copies the GOPATH path/revision but incorrectly sets the origin to `github.com/nats-io/gnatsd/vendor/github.com/nats-io/nuid`. However the `update` uses the `github.com/nats-io/gnatsd` revision, and correctly matches the `origin` source.

So it seems that the `update` command is running as expected and perhaps the `add` command is skipping a codepath which resolves the `vendor/github.../nuid` to its non-vendored version.  

I have more complex examples, but this one seemed simplest and was easier to follow. I might take another look at the govendor codebase and see if I can find the issue now that I think I've got a decent understanding of the problem.

Running on govendor `v1.0.4`, Go `1.6.3`

Hopefully this is helpful, let me know if more details are needed.

**Comment by kardianos** [comment] 2016-08-22 16:04
I haven't looked at this in detail, but yeah, looks like an origin issue. I'll see if I can reproduce locally and correct. Thanks.

**Comment by kardianos** [comment] 2016-09-01 14:26
@Ropes Would you be willing to test on master? I just committed a change that should prevent the origin from being set incorrectly.

**Comment by Ropes** [comment] 2016-09-01 16:02
Tested master / `350e502a5020652f167ecac3b492e2d571655504` and I'm not getting any discrepancy between `add +e` and `update +v`!!! :clap: :tada: Thanks for the fix! Really nice to only have the "origin" field defined on the packages which truly need it set.

:beers: on me next time you make it to PDXGo!

**Comment by kardianos** [comment] 2016-09-01 16:04
Thanks!

**Closed by kardianos** 2016-09-01 16:04 UTC
Labels: bug
