### ISSUE TITLE
feature: add subpackages in a swift with `package/...`

### ISSUE THREAD

**Issue by abourget** [kardianos/govendor#72] opened 2016-01-04 16:47 UTC
I was vendoring `github.com/raphael/goa` and its subpackages `goagen` and a few subpackages therein.. so I specified:

`govendor add github.com/raphael/goa/goagen/...`

`govendor` did add `goagen` to the `vendor.json` file.. but not its subpackages. It got me searching quite a bit since the errors didn't point to the missing repos at all (although that's a `go build` issue).

Since `govendor` accepted the `/...` notation, I would have expected it to do grab the subpackages. Otherwise, I would have expected an error :)

thanks for the tool, loving it otherwise :)

**Comment by kardianos** [comment] 2016-01-04 17:46
Hi @abourget , This is a known issue. I really need to tackle this quickly. This is a duplicate of some other issues, though I'll leave this open for easier finding. Right now the "/..."   only matches existing go packages. I need to add a switch or syntax to also blindly fetch the entire sub-tree.

I'll keep these issues posted. I hope to have this fixed at a tool level in a week. Until then just copy them into the vendor folder manually.

**Comment by kardianos** [comment] 2016-01-16 16:37
@abourget Would you test the "tree" branch? To match existing go packages, you use "/..." syntax. To add a full folder tree, use "/^" or the "-tree" option. More info in the README or help.

I hope to get some feedback on it before merging it in.

**Comment by abourget** [comment] 2016-01-18 19:16
the error I get is this one, which is tangential to the issue:

```
$ govendor add github.com/raphael/goa/goagen/...
Error: Package "...path/to/my/project/vendor/github.com/raphael/goa/goagen/codegen" already in vendor.
```

so it doesn't try the other directories.. I've hit this one many times.

**Comment by abourget** [comment] 2016-01-18 19:16
Now after removing `goa/goagen`, I get:

```
$ govendor add github.com/raphael/goa/goagen/^
Error: Cannot have a sub-tree "github.com/raphael/goa/goagen" contain sub-packages ["github.com/raphael/goa/goagen/gen_swagger" "github.com/raphael/goa/goagen/codegen" "github.com/raphael/goa/goagen/utils" "github.com/raphael/goa/goagen/meta" "github.com/raphael/goa/goagen/gen_schema" "github.com/raphael/goa/goagen/gen_client" "github.com/raphael/goa/goagen/gen_main" "github.com/raphael/goa/goagen/gen_js" "github.com/raphael/goa/goagen/gen_gen" "github.com/raphael/goa/goagen/gen_app"]
```

Not sure what to do here..

**Comment by abourget** [comment] 2016-01-18 19:18
Hmm.. after running: 

```
$ govendor remove github.com/raphael/goa/...
```

the `vendor.json` is still full of the `goa` packages.

**Comment by abourget** [comment] 2016-01-18 19:22
Running:

```
$ govendor add github.com/raphael/goa/^
Error: Cannot have a sub-tree "github.com/raphael/goa" contain sub-packages ["github.com/raphael/goa-middleware/cors" "github.com/raphael/goa/design" "github.com/raphael/goa/design/dsl"]
```

This is surprising, as `raphael/goa-middleware` is not the same subtree at all! :)

**Comment by abourget** [comment] 2016-01-18 19:26
So as you might see, my use case in particular is the `goa` package.. which, if you want to be able to rebuild your code, needs `goagen` to be present, along with a couple of other `goa_*` packages..

I wanted to be able to add those in a swift, so I though specifying `goa/...` would have brought them all in..

I appreciate the fact that `govendor` cleans up before doing the vendoring, not bringing along all sorts of files, but only things needed to build. So I would have liked `goa/...` to import only the packages.

I appreciate also the `/^` feature to add anything blindly.. I can see uses for that..

**Comment by abourget** [comment] 2016-01-18 19:27
So last shot, after removing things in `vendor/github.com/raphael/goa`, and running:

```
$ govendor add github.com/raphael/goa/^
Error: Cannot have a sub-tree "github.com/raphael/goa" contain sub-packages ["github.com/raphael/goa/design" "github.com/raphael/goa-middleware/cors" "github.com/raphael/goa/design/dsl"]
```

Perhaps it's because of the `goa-middleware` being in the way.. so I took it out, both from `vendor/` and from the `vendor.json` file.. and ran it again.. and got the same output:

```
$ govendor add github.com/raphael/goa/^
Error: Cannot have a sub-tree "github.com/raphael/goa" contain sub-packages ["github.com/raphael/goa/design" "github.com/raphael/goa/design/dsl" "github.com/raphael/goa-middleware/cors"]
```

so I'm stuck here :)

thanks for giving it a shot !

**Comment by kardianos** [comment] 2016-01-18 19:58
@abourget I probably have issue with a sanity check. Let me look into that and get back to you. Thanks for testing + error message!

**Comment by kardianos** [comment] 2016-01-18 20:55
@abourget I've just pushed a change to the "tree" branch that should resolve this issue. Thanks again for testing this.

**Comment by kardianos** [comment] 2016-01-22 17:01
This is now fixed on master.

**Closed by kardianos** 2016-01-22 17:01 UTC
